export const SEND_EMAIL ='SEND_EMAIL';
export const SEND_EMAIL_FAIL ='SEND_EMAIL_FAIL';
export const SEND_EMAIL_SUCCESS ='SEND_EMAIL_SUCCES';

/*export const FEED_ADD = 'FEED_ADD';
export const FEED_ADD_FAIL = 'FEED_ADD_FAIL';
export const FEED_ADD_SUCCESS = 'FEED_ADD_SUCCESS';

export const FEED_ADD_COMMENT = 'FEED_ADD_COMMENT';
export const FEED_ADD_COMMENT_FAIL = 'FEED_ADD_COMMENT_FAIL';
export const FEED_ADD_COMMENT_SUCCESS = 'FEED_ADD_COMMENT_SUCCESS';

export const FEED_REMOVE = 'FEED_REMOVE';
export const FEED_REMOVE_FAIL = 'FEED_REMOVE_FAIL';
export const FEED_REMOVE_SUCCESS = 'FEED_REMOVE_SUCCESS';*/
